import { z } from "zod";

export const UserSchema = z.object({
  login: z.string().nullish().catch(""),
  id: z.number().nullish().catch(0),
  node_id: z.string().nullish().catch(""),
  avatar_url: z.string().nullish().catch(""),
  gravatar_id: z.string().nullish().catch(""),
  url: z.string().nullish().catch(""),
  html_url: z.string().nullish().catch(""),
  followers_url: z.string().nullish().catch(""),
  following_url: z.string().nullish().catch(""),
  gists_url: z.string().nullish().catch(""),
  starred_url: z.string().nullish().catch(""),
  subscriptions_url: z.string().nullish().catch(""),
  organizations_url: z.string().nullish().catch(""),
  repos_url: z.string().nullish().catch(""),
  events_url: z.string().nullish().catch(""),
  received_events_url: z.string().nullish().catch(""),
  type: z.string().nullish().catch(""),
  site_admin: z.boolean().nullish(),
  name: z.string().nullish().catch(""),
  company: z.string().nullish().catch(""),
  blog: z.string().nullish().catch(""),
  location: z.string().nullish().catch(""),
  email: z.string().nullish().catch(""),
  hireable: z.boolean().nullish(),
  bio: z.string().nullish().catch(""),
  twitter_username: z.string().nullish().catch(""),
  public_repos: z.number().nullish().catch(0),
  public_gists: z.number().nullish().catch(0),
  followers: z.number().nullish().catch(0),
  following: z.number().nullish().catch(0),
  created_at: z.string().nullish().catch(""),
  updated_at: z.string().nullish().catch(""),
});
